# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-16 15:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCardReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, verbose_name='Credit card sale operation code')),
                ('reference_number', models.CharField(max_length=64, verbose_name='Credit card Reference number')),
                ('operation_number', models.CharField(max_length=128, verbose_name='Credit Card Reference operation number')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('canceled', 'Canceled'), ('paid', 'Paid')], default='pending', max_length=16, verbose_name='Sale status')),
                ('expiration_date', models.DateField(verbose_name='Credit Card Reference expiration date')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32, verbose_name='First name of the member')),
                ('last_name', models.CharField(max_length=32, verbose_name='Last name of the member')),
            ],
        ),
        migrations.AddField(
            model_name='creditcardreference',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_card_references', to='club.Member'),
        ),
    ]
