# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-17 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcardreference',
            name='expiration_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Credit Card Reference expiration date'),
        ),
        migrations.AlterField(
            model_name='creditcardreference',
            name='operation_number',
            field=models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='Credit Card Reference operation number'),
        ),
        migrations.AlterField(
            model_name='creditcardreference',
            name='reference_number',
            field=models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='Credit card Reference number'),
        ),
    ]
