# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-22 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_auto_20170517_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcardreference',
            name='expiration_date',
            field=models.CharField(blank=True, default=None, max_length=16, null=True, verbose_name='Credit Card Reference expiration date'),
        ),
    ]
