# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-22 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_auto_20170522_0948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditcardreference',
            name='expiration_date',
        ),
        migrations.AddField(
            model_name='creditcardreference',
            name='expiration_month',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='Credit Card Reference expiration year'),
        ),
        migrations.AddField(
            model_name='creditcardreference',
            name='expiration_year',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='Credit Card Reference expiration month'),
        ),
    ]
