# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-22 12:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangovirtualpos', '0011_auto_20170404_1424'),
        ('club', '0005_auto_20170522_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcardreference',
            name='virtual_pos',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='djangovirtualpos.VirtualPointOfSale', verbose_name='Credit Card Reference virtual point of sale'),
        ),
    ]
