# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-09 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='operation_number',
            field=models.CharField(default=1, max_length=128, verbose_name='Sale operation number'),
            preserve_default=False,
        ),
    ]
