# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-10 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_sale_operation_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='group_offer_discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Discount amount'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='group_offer_discount_type',
            field=models.CharField(blank=True, choices=[('percentage', 'Percentage'), ('absolute', 'Absolute')], default=None, max_length=32, null=True, verbose_name='Discount type (percent or absolute)'),
        ),
    ]
